[laptop]
"mod" = "Mod1"
"wm-setup" = "/home/scott/dotfiles/script/wm-setup-laptop"
"gaps-inner" = "15"
"gaps-outer" = "5"
"wallpaper" = "/home/scott/dotfiles/resources/wallpaper/squares-laptop.png"

[desktop]
"mod" = "Mod4"
"wm-setup" = "/home/scott/dotfiles/script/wm-setup-desktop"
"gaps-inner" = "20"
"gaps-outer" = "15"
"wallpaper" = "/home/scott/dotfiles/resources/wallpaper/squares-desktop.png"
