#!/usr/bin/env bash
_INPUT_FILE=$(mktemp)
i3-sensible-terminal -e nvim -c "set noswapfile" "$_INPUT_FILE"
sleep 0.2
head -c -1 $_INPUT_FILE | xdotool type --clearmodifiers --delay 0 --file -
rm $_INPUT_FILE
