#!/bin/sh

RES="2560x1440"
RR="144"

for output in $(xrandr | grep "DisplayPort" | sed -e "s/\(DisplayPort-.\).*/\1/"); do
  xrandr --output "$output" --mode "$RES" -r "$RR"
done

xcalib -d :0 $HOME/dotfiles/resources/dell.icc

xinput set-prop "Clearly Superior Technologies. CST Laser Trackball" 275 1

compton -b
