#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

BROWSER=/usr/bin/chromium
EDITOR=/usr/bin/vim

export GOROOT=/usr/local/go
export GOPATH=$HOME/src/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
export WINEDEBUG=-all

