#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export GOPATH=$HOME/src/go
export PATH=$PATH:$GOPATH/bin

alias ls='ls --color=auto'

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

if [ -f ~/.dir_colors ]; then
  eval "$(dircolors ~/.dir_colors)"
fi

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
	ssh-agent > ~/.ssh-agent-thing > /dev/null
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
	eval "$(<~/.ssh-agent-thing)" > /dev/null
fi

export BROWSER=firefox-developer-edition
export EDITOR=nvim

export PS1='\[\033[1;37m\]\[$(tput sgr0)\]\[\033[38;5;15m\]\[$(tput sgr0)\]\[\033[1;32m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]\[$(tput sgr0)\]\[\033[1;37m\]@\[$(tput sgr0)\]\[\033[38;5;15m\]\[$(tput sgr0)\]\[\033[1;32m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;15m\]\[$(tput sgr0)\]\[\033[1;37m\]$(basename "$(pwd)")\[$(tput sgr0)\]\[\033[38;5;15m\]\[$(tput sgr0)\]\[\033[1;32m\]\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[0;37m\] ⦔\[$(tput sgr0)\]\[\033[38;5;15m\] '
export PS2="\[$(tput sgr0)\]\[\033[0;37m\]⦔\[$(tput sgr0)\]\[\033[38;5;15m\] "

export PS1='\[\033[1;32m\]\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[0;35m\] ⦔\[$(tput sgr0)\]\[\033[38;5;15m\] '

export PS1='\[$(tput sgr0)\]\[\033[38;5;15m\]\[$(tput sgr0)\]\[\033[0;31m\]$(basename "$(pwd)")\[$(tput sgr0)\]\[\033[38;5;15m\]\[$(tput sgr0)\]\[\033[1;32m\]\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[0;35m\] ⦔\[$(tput sgr0)\]\[\033[38;5;15m\] '
